// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDsRnZBR4eZZ4ts7MMUCxvZJ_eRQr4Du8',
    appId: '1:658783323804:ios:b63586d8195a7154810f59',
    messagingSenderId: '658783323804',
    projectId: 'programming-app-55fbe',
    storageBucket: 'programming-app-55fbe.appspot.com',
    iosBundleId: 'com.example.programmingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4E9djzqAXzccwBObTpW74irHmhs9GmRc',
    appId: '1:658783323804:web:75b281379eacb0e6810f59',
    messagingSenderId: '658783323804',
    projectId: 'programming-app-55fbe',
    authDomain: 'programming-app-55fbe.firebaseapp.com',
    storageBucket: 'programming-app-55fbe.appspot.com',
    measurementId: 'G-4D6YF81Q81',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4E9djzqAXzccwBObTpW74irHmhs9GmRc',
    appId: '1:658783323804:web:75b281379eacb0e6810f59',
    messagingSenderId: '658783323804',
    projectId: 'programming-app-55fbe',
    authDomain: 'programming-app-55fbe.firebaseapp.com',
    storageBucket: 'programming-app-55fbe.appspot.com',
    measurementId: 'G-4D6YF81Q81',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDsRnZBR4eZZ4ts7MMUCxvZJ_eRQr4Du8',
    appId: '1:658783323804:ios:b63586d8195a7154810f59',
    messagingSenderId: '658783323804',
    projectId: 'programming-app-55fbe',
    storageBucket: 'programming-app-55fbe.appspot.com',
    iosBundleId: 'com.example.programmingApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEpL9YzT60fAtIo5dFEyqedTcmm3x2oFI',
    appId: '1:658783323804:android:b29b79177907581c810f59',
    messagingSenderId: '658783323804',
    projectId: 'programming-app-55fbe',
    storageBucket: 'programming-app-55fbe.appspot.com',
  );

}